#!/usr/bin/env bash
# gen_clangd.sh — minimal version when --query-driver is set in Zed
set -euo pipefail

COMPILE_DB=$(find . -maxdepth 5 -name "compile_commands.json" ! -path "*/\.*" -print -quit 2>/dev/null)
[[ -z "$COMPILE_DB" ]] && { echo "ERROR: compile_commands.json not found. Run 'idf.py build' first."; exit 1; }
echo "Found: $COMPILE_DB"

##############################################################################
# Collect project-wide -f/-m/-W flags from the compile DB
##############################################################################
mapfile -t ALL_FLAGS < <(python3 - "$COMPILE_DB" << 'PYEOF'
import json, sys, shlex
from collections import Counter

with open(sys.argv[1]) as f:
    cmds = json.load(f)

counts = Counter()
total = len(cmds)
for cmd in cmds:
    parts = cmd.get("arguments") or shlex.split(cmd.get("command", ""))
    for p in parts[1:]:
        if p.startswith(("-f", "-m", "-W")):
            counts[p] += 1

threshold = max(1, total * 0.10)
for flag, count in counts.items():
    if count >= threshold:
        print(flag)
PYEOF
)

##############################################################################
# Known-unsupported GCC/Xtensa flags
##############################################################################
KNOWN_UNSUPPORTED=(
    "-mlongcalls" "-mtext-section-literals"
    "-mfix-esp32-psram-cache-issue"
    "-mfix-esp32-psram-cache-strategy=memw"
    "-mabi=windowed"
    "-fno-tree-switch-conversion" "-fno-shrink-wrap" "-fno-jump-tables"
    "-fno-reorder-blocks" "-fno-reorder-functions"
    "-fno-printf-return-value" "-fstrict-volatile-bitfields"
    "-fmacro-prefix-map=.=."
    "-Wno-frame-address" "-Wno-maybe-uninitialized"
    "-Wno-format-truncation" "-Wno-format-overflow"
    "-Wno-stringop-truncation" "-Wno-stringop-overflow"
    "-Wno-restrict" "-Wno-alloc-size-larger-than"
    "-Wno-return-local-addr"
)

##############################################################################
# Dynamic detection via clang
##############################################################################
DYNAMIC_UNSUPPORTED=()
if command -v clang &>/dev/null; then
    for flag in "${ALL_FLAGS[@]}"; do
        if ! clang "$flag" -x c++ /dev/null -fsyntax-only \
                   -Werror=unknown-argument -Werror=unsupported-option 2>/dev/null; then
            DYNAMIC_UNSUPPORTED+=("$flag")
        fi
    done
fi

##############################################################################
# Merge & deduplicate
##############################################################################
declare -A _seen
FINAL_REMOVE=()
for f in "${KNOWN_UNSUPPORTED[@]}" "${DYNAMIC_UNSUPPORTED[@]}"; do
    if [[ -z "${_seen[$f]+_}" ]]; then _seen[$f]=1; FINAL_REMOVE+=("$f"); fi
done

##############################################################################
# Write .clangd  (no Add section needed — query-driver handles it)
##############################################################################
{
cat << HEADER
# Auto-generated by gen_clangd.sh — $(date '+%Y-%m-%d')
# System includes and target are handled by --query-driver in Zed settings.
HEADER

echo "CompileFlags:"
echo "  Remove:"
for f in "${FINAL_REMOVE[@]}"; do
    printf '    - "%s"\n' "$f"
done

cat << 'DIAG'

Diagnostics:
  Suppress:
    - "attribute_not_type_attr"
  UnusedIncludes: Strict
  MissingIncludes: Strict
  ClangTidy:
    Add:
      - modernize-use-trailing-return-type
      - readability-magic-numbers
      - bugprone-use-after-move
      - bugprone-dangling-handle
      - clang-analyzer-cplusplus.NewDeleteLeaks
      - cppcoreguidelines-smart-ptr
      - performance-unnecessary-value-param
      - performance-for-range-copy
      - bugprone-integer-division

Index:
  Background: Build
DIAG
} > .clangd

echo "✓ .clangd written (${#FINAL_REMOVE[@]} flags removed)."
echo "Make sure --query-driver is set in Zed → settings.json pointing at your xtensa compiler glob."
