#!/usr/bin/env bash
# generate_clangd.sh — Run from repo root
set -euo pipefail

FIRMWARE_DIR="firmware"
BUILD_DIR="${FIRMWARE_DIR}/build"
COMPILE_COMMANDS="${BUILD_DIR}/compile_commands.json"
CLANGD_OUT=".clangd"

if [[ ! -f "$COMPILE_COMMANDS" ]]; then
    echo "ERROR: $COMPILE_COMMANDS not found. Run 'idf.py reconfigure' or 'idf.py build' first." >&2
    exit 1
fi

# ── 1. Baseline flags: Always remove regardless of clang version ─────────────
# These are GCC/Xtensa specific or linker flags that consistently break clangd parsing.
BASELINE_REMOVE=(
    "--specs=*"
    "-mlongcalls"
    "-mtext-section-literals"
    "-fno-tree-switch-conversion"
    "-fstrict-volatile-bitfields"
    "-fno-jump-tables"
    "-fno-shrink-wrap"
    "-fno-reorder-functions"
    "-fstack-reuse=*"
    "-Wno-frame-address"
    "-fmacro-prefix-map=*"
    "-fdebug-prefix-map=*"
    "-Wl,*"
)

# ── 2. Dynamically detect additional unknown flags ───────────────────────────
echo "Scanning $COMPILE_COMMANDS for candidate GCC flags..."
ALL_FLAGS=$(python3 - "$COMPILE_COMMANDS" <<'EOF'
import json, sys, re
with open(sys.argv[1]) as f:
    cmds = json.load(f)
flags = set()
for entry in cmds:
    for flag in entry.get("arguments", entry.get("command", "").split()):
        # Capture standard flag prefixes. Convert values (e.g. -O2) to wildcards if needed,
        # but for simplicity, we capture the exact flag to test it.
        if re.match(r'^-[fmWO]', flag):
            flag = re.sub(r'=[^=]+$', '=*', flag)
            flags.add(flag)
for f in sorted(flags):
    print(f)
EOF
)

echo "Probing clang for unrecognised flags..."
DYNAMIC_FLAGS=()
while IFS= read -r flag; do
    already=0
    for b in "${BASELINE_REMOVE[@]}"; do
        [[ "$b" == "${flag/=*/=*}" || "$b" == "$flag" ]] && already=1 && break
    done
    [[ $already -eq 1 ]] && continue

    probe="${flag/=\*/=placeholder}"
    # Use standard clang to probe for flag support
    if clang -x c /dev/null -fsyntax-only "$probe" 2>&1 \
        | grep -qiE "unknown|unrecognized|unsupported|not supported|unused argument"; then
        DYNAMIC_FLAGS+=("    - \"${flag}\"")
    fi
done <<< "$ALL_FLAGS"

# ── 3. Write .clangd ─────────────────────────────────────────────────────────
BASELINE_YAML=""
for f in "${BASELINE_REMOVE[@]}"; do
    BASELINE_YAML+="    - \"${f}\""$'\n'
done

cat > "$CLANGD_OUT" <<YAML
# .clangd — Auto-generated by generate_clangd.sh
# Regenerate after major ESP-IDF updates or compiler changes.

CompileFlags:
  Add:
    - "-Wno-unknown-warning-option"
  Remove:
    # --- Baseline GCC/Xtensa overrides ---
${BASELINE_YAML}
    # --- Dynamically detected unsupported flags ---
$(printf '%s\n' "${DYNAMIC_FLAGS[@]:-}")

Diagnostics:
  UnusedIncludes: Strict
  MissingIncludes: Strict
  ClangTidy:
    Add:
      - bugprone-*
      - performance-*
      - readability-*
      - modernize-*
      - portability-*
    Remove:
      # Exclude highly opinionated or noisy checks
      - modernize-use-trailing-return-type
      - readability-magic-numbers
      - bugprone-reserved-identifier
      - readability-braces-around-statements
      - readability-identifier-length
      - readability-function-cognitive-complexity
      - modernize-macro-to-enum # ESP-IDF heavily relies on C macros

Index:
  Background: Build

InlayHints:
  Enabled: Yes
  ParameterNames: Yes
  DeducedTypes: Yes
  Designators: Yes

Hover:
  ShowAKA: Yes
YAML

echo ""
echo "Successfully generated: $CLANGD_OUT"
echo "  Baseline: ${#BASELINE_REMOVE[@]} flags removed."
echo "  Dynamic:  ${#DYNAMIC_FLAGS[@]} additional flags removed."
